### Add the key you will get here and run "environment-config-generate" in the terminal
environment_config:
  path: environment_config.dart
  class: EnvironmentConfig
  fields:
    open_charge_api_key:
      type: String
      description: Open Charge API Key
      required: true
      default: "<Your-Api-Key>"
      dotenv: true
      config_field: false
      first_key:
        env_var: PATH
  imports:
    - package:dotenv/dotenv.dart